name: Deploy Ubuntu Desktop with NoVNC

on:
  workflow_dispatch:  # 手动触发
  # 如果需要定时触发，可以取消下面的注释
  # schedule:
  #   - cron: '0 */6 * * *'  # 每6小时运行一次

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Ubuntu Desktop with NoVNC
      run: |
        # 安装必要的依赖
        sudo apt-get update
        sudo apt-get install -y \
          xfce4 \
          xfce4-goodies \
          x11vnc \
          novnc \
          websockify \
          firefox \
          git \
          curl \
          wget \
          gnome-terminal \
          net-tools \
          dbus-x11
        
        # 创建VNC密码文件
        mkdir -p ~/.vnc
        echo "asdf1234" | vncpasswd -f > ~/.vnc/passwd
        chmod 600 ~/.vnc/passwd
        
        # 配置XFCE桌面环境
        echo "export DISPLAY=:1" >> ~/.bashrc
        echo "export LANG=en_US.UTF-8" >> ~/.bashrc
        echo "export LANGUAGE=en_US:en" >> ~/.bashrc
        
        # 设置自动启动XFCE的脚本
        cat > ~/start_desktop.sh << 'EOF'
        #!/bin/bash
        export DISPLAY=:1
        Xvfb :1 -screen 0 1280x720x24 &
        sleep 2
        startxfce4 &
        sleep 5
        x11vnc -display :1 -noxdamage -forever -shared -rfbport 5900 -passwd asdf1234 &
        sleep 2
        /usr/share/novnc/utils/launch.sh --vnc localhost:5900 --listen 6080 &
        EOF
        
        chmod +x ~/start_desktop.sh

    - name: Download and setup Cloudflared
      run: |
        # 下载cloudflared
        wget https://github.com/cloudflare/cloudflared/releases/download/2025.11.1/cloudflared-linux-amd64
        chmod +x cloudflared-linux-amd64
        sudo mv cloudflared-linux-amd64 /usr/local/bin/cloudflared
        
        # 创建cloudflared配置文件
        mkdir -p ~/.cloudflared
        cat > ~/.cloudflared/config.yml << 'EOF'
        tunnel: $(echo ${GITHUB_REPOSITORY##*/}-${GITHUB_RUN_ID} | tr '/' '-')
        credentials-file: /home/runner/.cloudflared/credentials.json
        ingress:
          - hostname: $(echo ${GITHUB_REPOSITORY##*/}-${GITHUB_RUN_ID} | tr '/' '-').trycloudflare.com
            service: http://localhost:6080
          - service: http_status:404
        EOF

    - name: Start NoVNC and Cloudflared
      run: |
        # 启动桌面环境
        bash ~/start_desktop.sh &
        
        # 等待NoVNC启动
        sleep 10
        
        # 启动cloudflared隧道
        echo "正在启动cloudflared隧道..."
        cloudflared tunnel --url http://localhost:6080 2>&1 | tee cloudflared.log &
        
        # 等待隧道建立
        sleep 15
        
        # 从日志中提取访问URL
        if grep -q "trycloudflare.com" cloudflared.log; then
          echo "隧道已建立！"
          TUNNEL_URL=$(grep -o 'https://[^ ]*\.trycloudflare\.com' cloudflared.log | head -1)
          echo "访问地址: $TUNNEL_URL"
          echo "VNC密码: asdf1234"
          
          # 将URL设置为GitHub Actions输出
          echo "NOVNC_URL=$TUNNEL_URL" >> $GITHUB_ENV
          echo "::notice title=访问信息::桌面已启动！访问地址: $TUNNEL_URL VNC密码: asdf1234"
        else
          echo "警告: 无法从日志中提取隧道URL"
          echo "请检查cloudflared.log文件查看详细信息"
        fi

    - name: Keep alive
      run: |
        echo "桌面环境正在运行中..."
        echo "按 Ctrl+C 停止工作流"
        echo "访问信息:"
        echo "URL: ${{ env.NOVNC_URL }}"
        echo "密码: asdf1234"
        
        # 保持工作流运行（最多6小时）
        timeout 6h bash -c 'while true; do sleep 300; done'
